version: '3.9'

services:
  publisher:
    image: andriiuni/events:latest
    restart: always
    env_file:
      - .env.publisher
    depends_on:
      - gateway

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    env_file:
      - ./apps/gateway/.env
    command: npm run start:gateway:dev
    ports:
      - '3001:3001'
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    command: >
      -js
      -sd /data
      -m 8222

volumes:
  nats-data: