version: '3.9'

services:
  publisher:
    image: andriiuni/events:latest
    restart: always
    env_file:
      - .env.publisher
    depends_on:
      - gateway

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    env_file:
      - ./apps/gateway/.env
    command: npm run start:gateway:dev
    ports:
      - '3001:3001'
    depends_on:
      - nats

  fb-collector:
    build:
      context: .
      dockerfile: ./apps/fb-collector/Dockerfile
      target: development
    env_file:
      - ./apps/fb-collector/.env
    command: sh -c "npx prisma migrate deploy --schema=libs/common/src/prisma/ && npm run start:fb-collector:dev"
    ports:
      - '3002:3002'
    depends_on:
      - nats

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data
    command: >
      -js
      -sd /data
      -m 8222

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  nats-data:
  postgres_data: