{
 "title": "Monitoring",
 "time": { "from": "2025-06-12T11:04:40.113Z", "to": "2025-06-12T13:59:54.545Z" },
 "panels": [
  {
   "title": "Reporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "execution_latency_bucket{category=\"getEventsCount\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "execution_latency_bucket{category=\"getEventsDemographics\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "execution_latency_bucket{category=\"getEventsRevenue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(accepted_events{job=\"fb-collector\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(accepted_events{job=\"ttk-collector\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "downsampler": "mean",
     "expression": "$A + $B",
     "type": "math",
     "upsampler": "fillna"
    },
    {
     "expr": "rate(processed_events{job=\"fb-collector\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(processed_events{job=\"ttk-collector\"}[1m])",
     "legendFormat": "__auto"
    },
    { "expression": "$D+$E\n", "type": "math" },
    {
     "expr": "rate(failed_events{job=\"ttk-collector\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(failed_events{job=\"fb-collector\"}[1m])",
     "legendFormat": "__auto"
    },
    { "expression": "$H+$G", "type": "math" }
   ]
  },
  {
   "title": "Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "accepted_events{job=\"gateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "processed_events{job=\"gateway\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "failed_events{job=\"gateway\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}